# -----------------------------------------------
# Jekyll Configuration
# -----------------------------------------------

markdown: rdiscount
permalink: pretty
pygments: true

# -----------------------------------------------
# Site-specific Settings
# -----------------------------------------------

author: John Doe
author_email: john@doe.com
title: Jekyll Zurb Quickstart
url: http://localhost:4000
